---
- name: Hello World
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      condition: event.i == 1
      action:
         run_job_template:
           name: Git-Playbook
           organization: Default
           retries: 1
           delay: 10
